### ISSUE TITLE
Able to set custom port

### ISSUE THREAD

**Issue by necccc** [Elethom/homebridge-gree-heatercooler-v2#18]
the `homebridge-gree-heatercooler` worked - somewhat hectic - by using a different port on the Gree units we have (port 8014)

I'd love to try out the v2 version, but it seems it's fixed on using port 7000.
Could we have an option to set the port?

**Comment by Elethom** [comment]
Hi, I created a commit solving this issue. Please run:
```
npm install -g https://github.com/Elethom/homebridge-gree-heatercooler-v2.git
```
to install the latest version and restart Homebridge to use it.

I hope this helps. I no longer have a test environment anymore since I couldn't afford my old apartment where I used to have Gree AC units installed. I'd really appreciate it if you can report back to me on any issues on this project so I can publish newer versions.

And I recommend you post an issue on this repo: [gree-remote](https://github.com/tomikaa87/gree-remote) I based my project on this protocol and it didn't mention anything about other possible ports. It may help others working on this protocol.

Thank you.

**Comment by Elethom** [comment]
Closed due to inactivity.
