### ISSUE TITLE
Adding contact sensors for AC on/off - open/closed

### ISSUE THREAD

**Issue by clickbg** [Elethom/homebridge-gree-heatercooler-v2#27]
Hi,

Thank you for the amazing Gree integration, the plugin works like a charm!

Is it possible to add a contact sensor (as an option) which changes when the AC is on or off?
Example plugin is the Roomba integration which has multiple contact sensors for running, bin full and so on - https://github.com/karlvr/homebridge-roomba2
My use-case is automation, for example I have separate heat source (radiators) which can be stopped automatically if the AC is running as well - contact open and then started when the AC is off - contact closed.

Thank you again for the plugin!

**Comment by Elethom** [comment]
Thanks for the advice! But the built-in automation supports that. If you really need it for something else specifically, I recommend you make your own fork. I wouldn't take the function in due to its rare use case.

You can install your own fork with `npm install -g [your repo]` after removing the original one.
