### ISSUE TITLE
New Error in  v3 (maybe v2)

### ISSUE THREAD

**Issue by RichardTHF** [Elethom/homebridge-gree-heatercooler-v2#6]
![image](https://user-images.githubusercontent.com/5789676/108697360-bb413600-753d-11eb-8bc2-071bdb12aca2.png)

So getting this weird issue since I updated to the latest version of the plugin, I have rolled back a few versions and it seems to have been introduced in version 2.0

https://paste.richardjdavies.com/?7e50c19d46d08114#9JeeiytkbyKR8CUG5qT2Zpqty4NrNEiStBdBDQZ6RzCK

^ Debug Logs at the bottom ^

**Comment by Elethom** [comment]
Temperature can not be set to value lower than 16.

**Comment by Elethom** [comment]
My guess is you set the temperature using AC’s own remote to a Fahrenheit value below it, am I right?

**Comment by RichardTHF** [comment]
Not that I am aware of, my remote is in celcius...  I also never use the remote as this works so perfectly ;)

**Comment by Elethom** [comment]
Well, in that case, the warning should be gone if you adjust the temperature to some other value and then back.

**Comment by RichardTHF** [comment]
Got it, cheers :)

**Comment by puja108** [comment]
I had the same issue and the above suggested trick fixed it, important detail as to use Apple Home to change the temperature to something else and then back to 16, using the AC remote or the manufacturer app did not fix it. Not sure how common this issue is, but might want to add the fix to a FAQ section in Readme. If you want I can also provide a PR for that.
